#!/bin/bash
# 🚀 INICIAR MÓDULO DE ESTOQUE - GUIA RÁPIDO

echo "╔════════════════════════════════════════════════╗"
echo "║   VAREJIX - MÓDULO DE GESTÃO DE ESTOQUE       ║"
echo "║   Status: ✅ PRONTO PARA INICIAR              ║"
echo "╚════════════════════════════════════════════════╝"
echo ""

echo "📋 ARQUIVOS IMPLEMENTADOS:"
echo "  ✅ 3 Páginas principais (Movements, Levels, Reports)"
echo "  ✅ 3 Componentes reutilizáveis (Form, Table, Badge)"
echo "  ✅ 25+ Endpoints backend"
echo "  ✅ 6 Relatórios avançados"
echo "  ✅ Sistema de alertas automáticos"
echo "  ✅ 4 Documentações completas"
echo ""

echo "🗂️  ESTRUTURA DE DADOS:"
echo "  • stock_locations    → Depósitos e lojas"
echo "  • stock_movements    → Histórico de movimentações"
echo "  • stock_levels       → Estoque atual por local"
echo "  • stock_batches      → Lotes com validade"
echo "  • stock_alerts       → Alertas automáticos"
echo ""

echo "🎯 COMO INICIAR:"
echo ""
echo "1️⃣  TERMINAL 1 - Backend Express (porta 3000):"
echo "   npm run mock:express:watch"
echo ""
echo "2️⃣  TERMINAL 2 - Frontend Vite (porta 5173):"
echo "   npm run dev"
echo ""
echo "3️⃣  LOGIN:"
echo "   Usuário: admin"
echo "   Senha: password"
echo ""
echo "4️⃣  ACESSAR ESTOQUE:"
echo "   Menu Lateral → Estoque"
echo "   • Movimentações       (/stock/movements)"
echo "   • Níveis de Estoque   (/stock/levels)"
echo "   • Relatórios          (/stock/reports)"
echo ""

echo "📚 DOCUMENTAÇÃO:"
echo "  📖 Guia Completo:    docs/MODULO_ESTOQUE.md"
echo "  ⚡ Quick Reference:  docs/ESTOQUE_GUIA_RAPIDO.md"
echo "  🏗️  Arquitetura:      docs/ESTOQUE_ARQUITETURA.md"
echo "  📖 Casos de Uso:     docs/ESTOQUE_CASOS_USO.md"
echo "  📋 Resumo Final:     ESTOQUE_RESUMO_FINAL.md"
echo ""

echo "✨ FUNCIONALIDADES PRINCIPAIS:"
echo "  📦 Registrar entradas (compra, devolução, ajuste)"
echo "  📤 Registrar saídas (venda, perda, transferência)"
echo "  ⚠️  Alertas automáticos (ruptura, baixo, alto)"
echo "  📊 6 Relatórios com CSV export"
echo "  🔐 CSRF protection em todas operações"
echo "  👤 Autenticação e auditoria completa"
echo ""

echo "🧪 DADOS DE TESTE:"
echo "  • 10 produtos cadastrados"
echo "  • 4 locais de estoque"
echo "  • 5 movimentações de exemplo"
echo "  • 12 níveis com alertas"
echo ""

echo "🎨 RECURSOS VISUAIS:"
echo "  🔴 RUPTURA     (vermelho)"
echo "  🟠 Estoque Baixo (laranja)"
echo "  🔵 Estoque Alto  (azul)"
echo "  🟢 OK            (verde)"
echo ""

echo "🚀 INICIANDO..."
echo ""
echo "⏰ WINDOWS POWERSHELL? Use:"
echo "   Terminal 1: npm run mock:express:watch"
echo "   Terminal 2: npm run dev"
echo ""
echo "✅ Tudo pronto! Acesse http://localhost:5173"
echo ""
